name: CI

on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: macos-26
    timeout-minutes: 30
    env:
      SECRET_URL: "${{ secrets.SECRET_URL }}"
      SECRET_KEY: "${{ secrets.SECRET_KEY }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.fastlane
          key: session-${{ github.run_id }}
          restore-keys: |
            session

      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: '3.14.1'
        
      - name: Sign
        run: |
          PYTHONUNBUFFERED=1 ./sign.py
